# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='lien',
            field=models.CharField(default='reunion', max_length=30),
            preserve_default=False,
        ),
    ]
