# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20160715_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='lien',
            field=models.CharField(max_length=30),
        ),
    ]
