# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_remove_categorie_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='lien',
            field=models.CharField(default='default_link', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
