# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_categorie_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='lien',
        ),
    ]
