# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_remove_categorie_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.TextField(),
        ),
    ]
