# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_auto_20160716_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
