# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 20:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BassinVersant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_zone', models.CharField(max_length=4)),
                ('libelle', models.CharField(max_length=125)),
                ('id_nd_exut', models.BigIntegerField()),
                ('c_hyd_cdo', models.CharField(max_length=8)),
                ('pkhexut', models.IntegerField()),
                ('lib_ss_sec', models.CharField(max_length=125)),
                ('lib_sect', models.CharField(max_length=125)),
                ('lib_region', models.CharField(max_length=125)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=2154)),
            ],
        ),
    ]
