# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 20:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hydro', models.CharField(max_length=8)),
                ('toponyme', models.CharField(max_length=127)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=2154)),
            ],
        ),
    ]
