# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 20:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_cdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdo',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=2154),
        ),
    ]
