# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20160919_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_12', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2154)),
            ],
        ),
    ]
