# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_clc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdo',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
