# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 17:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_cdo_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_com', models.CharField(max_length=50)),
                ('nbre_capta', models.BigIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=2154)),
            ],
        ),
        migrations.CreateModel(
            name='Ipr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sation', models.BigIntegerField()),
                ('code_onema', models.BigIntegerField()),
                ('abscisse', models.BigIntegerField()),
                ('ordonnee', models.BigIntegerField()),
                ('abscisse_1', models.BigIntegerField()),
                ('ordonne_1', models.BigIntegerField()),
                ('localisation', models.CharField(max_length=254)),
                ('code_point', models.CharField(max_length=254)),
                ('abscisse_p', models.BigIntegerField()),
                ('ordonne_2', models.BigIntegerField()),
                ('departement', models.BigIntegerField()),
                ('code_hydro', models.CharField(max_length=254)),
                ('riviere', models.CharField(max_length=254)),
                ('lieudit', models.CharField(max_length=254)),
                ('region', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=2154)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bassin_cod', models.CharField(max_length=2)),
                ('region_nom', models.CharField(max_length=17)),
                ('departemen', models.CharField(max_length=2)),
                ('code_uh', models.CharField(max_length=50)),
                ('nom_uh', models.CharField(max_length=80)),
                ('agglo_code', models.CharField(max_length=12)),
                ('agglo_nom', models.CharField(max_length=48)),
                ('nbre_step', models.FloatField()),
                ('nbre_step_field', models.FloatField()),
                ('taille_agg', models.FloatField()),
                ('step_code', models.CharField(max_length=12)),
                ('step_nom', models.CharField(max_length=48)),
                ('coord_x_de', models.FloatField()),
                ('coord_y_de', models.FloatField()),
                ('step_activ', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=2154)),
            ],
        ),
    ]
