# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_captage_ipr_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ipr',
        ),
    ]
