#-*- coding: utf-8 -*-

"""
Django settings for sivb project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=g&h(etp7ywu^7qwnty#_pp7$v-n7pf1ta6s&$pfp3vfc)p-xp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres', # for the 'search' method in the actualite APP
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.contrib.gis',
    'actualites',
    'archives',
    'map',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sivb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		# to get the context data
		'sivb.context_processors.get_info_block_nav',
		'sivb.context_processors.get_info_articles',
		'sivb.context_processors.get_info_footer',
            ],
        },
    },
]

WSGI_APPLICATION = 'sivb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'sivr',
        'USER': 'postgres',
        'PASSWORD': 'AJ9MUDjr',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Variable for the web display

NUMBER_OF_MINIARTICLE = 6 # for the aside block

ACTUALITE_PAGINATION_BY = 2 # for actualites APP
import os
from django.conf import settings

DEBUG = False 
TEMPLATE_DEBUG = False
ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ['redelan.hd.free.fr']
DATABASES = settings.DATABASES
#SECRET_KEY = os.environ['SECRET_KEY']
SECRET_KEY = 'bonjour'
SESSION_COOKIE_SECURE = True


# database
"""
import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
"""

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# Extra places for collectstatic to find static files.
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),
#DOMAINE_NAME = 'redelan.hd.free.fr/sivr/'
#STATICFILES_LOCATION = 'static'
#MEDIAFILES_LOCATION = 'media'
#STATIC_URL = "https://%s/%s/" % (DOMAINE_NAME, STATICFILES_LOCATION)
#STATIC_ROOT = "https://%s/static" % DOMAINE_NAME
#MEDIA_URL = "https://%s/%s/" % (DOMAINE_NAME, MEDIAFILES_LOCATION)

