# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_auto_20160604_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(verbose_name='Date de parution'),
        ),
    ]
