# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0005_auto_20160606_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icone',
            field=models.ImageField(upload_to='actualites/logos/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/images/'),
        ),
    ]
