# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0006_auto_20160624_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='iconeEncodedImage',
            field=models.TextField(default='fdfsdf'),
            preserve_default=False,
        ),
    ]
