# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0007_categorie_iconeencodedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='icone',
        ),
    ]
